steps:
  # Build the module.
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/chukaofili/gitops-apps']
    dir: 'examples/hello_world'
    env: ['HOME=/workspace']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['ls', '-la']
    dir: 'examples/hello_world'
    env: ['HOME=/workspace']
  # - name: gcr.io/k8s-skaffold/skaffold
  #   args: ['skaffold', 'build', '--default-repo', 'gcr.io/ms-clients-2018']
  #   env: ['HOME=/workspace']
  #   dir: 'examples/hello_world'