steps:
  # Build the module.
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/chukaofili/gitops-apps']
  - name: gcr.io/k8s-skaffold/skaffold
    args: ['skaffold', 'build', '--default-repo', 'gcr.io/ms-clients-2018']