
apiVersion: skaffold/v2beta8
kind: Config
build:
  tagPolicy:
    gitCommit: {
      variant: Tags
    }
  artifacts:
  - image: nodejs-guestbook-backend
    context: src/backend
    sync:
      infer:
      - '**/*'
  - image: nodejs-guestbook-frontend
    context: src/frontend
    sync:
      infer:
      - '**/*'
deploy:
  kubectl:
    manifests:
    - ./k8s/*
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
    artifacts:
    - image: nodejs-guestbook-backend
      context: src/backend
      sync:
        infer:
        - '**/*'
      kaniko:
        cache: {}
    - image: nodejs-guestbook-frontend
      context: src/frontend
      sync:
        infer:
        - '**/*'
      kaniko:
        cache: {}