
apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    gitCommit: {
      variant: Tags
    }
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: gcr.io/ms-clients-2018/nodejs-guestbook-backend
    context: src/backend
    sync:
      infer:
      - '**/*'
  - image: gcr.io/ms-clients-2018/nodejs-guestbook-frontend
    context: src/frontend
    sync:
      infer:
      - '**/*'
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./k8s/*
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
    artifacts:
    - image: nodejs-guestbook-backend
      context: src/backend
      sync:
        infer:
        - '**/*'
      kaniko:
        cache: {}
    - image: nodejs-guestbook-frontend
      context: src/frontend
      sync:
        infer:
        - '**/*'
      kaniko:
        cache: {}