apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-guestbook-backend
  labels:
    app: nodejs-guestbook
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-guestbook
      tier: backend
  template:
    metadata:
      labels:
        app: nodejs-guestbook
        tier: backend
    spec:
     containers:
      - name: backend
        image: nodejs-guestbook-backend
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_DB_ADDR
          value: "mongodb.system:27017"
